# 01. Exploratory Data Analysis & Data Cleaning
**Project:** Car Price Prediction (Otomoto Dataset)  
**Goal:** Analyze data distributions, handle missing values and potentioal duplicates.

## 1. Imports and environment setup

In [2]:
import pandas as pd
import numpy as np

from pathlib import Path

## 2. Configuration and Paths

In [3]:
BASE_PATH = Path.cwd().parent
RAW_DATA_PATH = BASE_PATH / "data" / "raw" / "Car_sale_ads.csv"

## 3. Data Loading

In [6]:
df_raw = pd.read_csv(RAW_DATA_PATH)
df_raw.head(20)

,Index,Price,Currency,Condition,Vehicle_brand,Vehicle_model,Vehicle_version,Vehicle_generation,Production_year,Mileage_km,...,Transmission,Type,Doors_number,Colour,Origin_country,First_owner,First_registration_date,Offer_publication_date,Offer_location,Features
0,0,86200,PLN,New,Abarth,595,NaN,NaN,2021,1.0,...,Manual,small_cars,3.0,gray,NaN,NaN,NaN,04/05/2021,"ul. Jubilerska 6 - 04-190 Warszawa, Mazowiecki...",[]
1,1,43500,PLN,Used,Abarth,Other,NaN,NaN,1974,59000.0,...,Manual,coupe,2.0,silver,NaN,NaN,NaN,03/05/2021,"kanonierska12 - 04-425 Warszawa, Rembertów (Po...",[]
2,2,44900,PLN,Used,Abarth,500,NaN,NaN,2018,52000.0,...,Automatic,small_cars,3.0,silver,NaN,NaN,NaN,03/05/2021,"Warszawa, Mazowieckie, Białołęka","['ABS', 'Electric front windows', 'Drivers air..."
3,3,39900,PLN,Used,Abarth,500,NaN,NaN,2012,29000.0,...,Manual,small_cars,3.0,gray,NaN,NaN,NaN,30/04/2021,"Jaworzno, Śląskie","['ABS', 'Electric front windows', 'Drivers air..."
4,4,97900,PLN,New,Abarth,595,NaN,NaN,2021,600.0,...,Manual,small_cars,3.0,blue,NaN,NaN,NaN,30/04/2021,"ul. Gorzysława 9 - 61-057 Poznań, Nowe Miasto ...","['ABS', 'Electrically adjustable mirrors', 'Pa..."
5,5,62950,PLN,Used,Abarth,595,NaN,NaN,2016,46060.0,...,Manual,small_cars,3.0,gray,Germany,Yes,15/03/2016,30/04/2021,"Modlińska 157 - 03-186 Warszawa, Białołęka (Po...","['ABS', 'Electric front windows', 'Drivers air..."
6,6,69900,PLN,Used,Abarth,595,NaN,NaN,2021,2900.0,...,Manual,small_cars,2.0,black,Germany,NaN,25/02/2021,29/04/2021,"Żary, żarski, Lubuskie",[]
7,7,69900,PLN,Used,Abarth,500,NaN,NaN,2019,20000.0,...,Manual,small_cars,3.0,white,Poland,Yes,NaN,29/04/2021,"Ojcowska 2 - 02-918 Warszawa, Mokotów (Polska)","['ABS', 'Electrically adjustable mirrors', 'Pa..."
8,8,120750,PLN,New,Abarth,595,NaN,NaN,2021,1.0,...,Manual,small_cars,3.0,blue,NaN,NaN,NaN,03/05/2021,"ul. Gorzysława 9 - 61-057 Poznań, Nowe Miasto ...","['ABS', 'Electrically adjustable mirrors', 'Pa..."
9,9,93100,PLN,New,Abarth,595,NaN,NaN,2021,1.0,...,Manual,small_cars,3.0,gray,NaN,NaN,NaN,03/05/2021,"ul. Gorzysława 9 - 61-057 Poznań, Nowe Miasto ...","['ABS', 'Electrically adjustable mirrors', 'Pa..."
10,10,67000,PLN,Used,Abarth,595,NaN,NaN,2018,38000.0,...,Manual,small_cars,3.0,white,Poland,NaN,NaN,25/04/2021,"Gdańsk, Pomorskie, Śródmieście","['ABS', 'Electric front windows', 'Passengers ..."
11,11,31900,PLN,Used,Abarth,Grande Punto,NaN,NaN,2010,179000.0,...,Manual,city_cars,3.0,white,NaN,NaN,29/04/2010,25/04/2021,"Bielsko-Biała, Śląskie","['ABS', 'Electric front windows', 'Drivers air..."
12,12,70000,PLN,Used,Abarth,595,NaN,NaN,2017,18470.0,...,Manual,small_cars,3.0,black,Germany,NaN,09/11/2017,04/05/2021,"Rzeszów, Podkarpackie","['ABS', 'Immobilizer', 'Factory radio', 'ASR (..."
13,13,38500,PLN,Used,Abarth,500,NaN,NaN,2015,117000.0,...,Manual,city_cars,3.0,gray,NaN,Yes,NaN,04/05/2021,"Sulechów, zielonogórski, Lubuskie","['ABS', 'Bluetooth', 'Rain sensor', 'Panoramic..."
14,14,41400,PLN,Used,Abarth,500,NaN,NaN,2014,79233.0,...,Manual,small_cars,3.0,red,Poland,NaN,18/05/2015,04/05/2021,"Koszalin, Zachodniopomorskie","['ABS', 'Electric front windows', 'Drivers air..."
15,15,36000,PLN,Used,Abarth,Other,NaN,NaN,2012,82000.0,...,Manual,city_cars,3.0,black,Poland,NaN,27/04/2012,23/04/2021,"Zgorzelec, zgorzelecki, Dolnośląskie","['ABS', 'Electric front windows', 'Power steer..."
16,16,80900,PLN,New,Abarth,595,NaN,NaN,2020,1.0,...,Manual,small_cars,3.0,red,NaN,NaN,NaN,29/04/2021,"ul. Jubilerska 6 - 04-190 Warszawa, Mazowiecki...",[]
17,17,127921,PLN,New,Abarth,595,NaN,NaN,2021,3.0,...,Manual,small_cars,3.0,blue,NaN,NaN,NaN,29/04/2021,"ul. Karkonoska 45 - 53-015 Wrocław, Dolnośląsk...","['ABS', 'Electrically adjustable mirrors', 'Pa..."
18,18,70900,PLN,Used,Abarth,595,NaN,NaN,2019,11000.0,...,Manual,small_cars,2.0,yellow,Poland,Yes,NaN,04/05/2021,"Lublin, Lubelskie","['ABS', 'Electric front windows', 'Drivers air..."
19,19,22900,PLN,Used,Abarth,Grande Punto,NaN,NaN,2009,182000.0,...,Manual,city_cars,3.0,white,Germany,NaN,29/05/2009,04/05/2021,"Jarocin, jarociński, Wielkopolskie","['ABS', 'Electric front windows', 'Drivers air..."

In [8]:
df_raw.shape

(208304, 25)

In [33]:
#general information about hte dataset

df_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 208304 entries, 0 to 208303
Data columns (total 25 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Index                    208304 non-null  int64
 1   Price                    208304 non-null  int64
 2   Currency                 208304 non-null  str
 3   Condition                208304 non-null  str
 4   Vehicle_brand            208304 non-null  str
 5   Vehicle_model            208304 non-null  str
 6   Vehicle_version          138082 non-null  str
 7   Vehicle_generation       147860 non-null  str
 8   Production_year          208304 non-null  int64
 9   Mileage_km               207321 non-null  float64
 10  Power_HP                 207661 non-null  float64
 11  Displacement_cm3         206338 non-null  float64
 12  Fuel_type                208304 non-null  str
 13  CO2_emissions            94047 non-null   float64
 14  Drive                    193228 non-null  str
 15  Transmission             207825 non-null  str
 16  Type                     208304 non-null  str
 17  Doors_number             206817 non-null  float64
 18  Colour                   208304 non-null  str
 19  Origin_country           118312 non-null  str
 20  First_owner              65094 non-null   str
 21  First_registration_date  86445 non-null   str
 22  Offer_publication_date   208304 non-null  str
 23  Offer_location           208304 non-null  str
 24  Features                 208304 non-null  str
dtypes: float64(5), int64(3), str(17)
memory usage: 39.7 MB

In [34]:
#Information about numerical columns

df_raw.describe()

,Index,Price,Production_year,Mileage_km,Power_HP,Displacement_cm3,CO2_emissions,Doors_number
count,208304.000000,2.083040e+05,208304.000000,2.073210e+05,207661.000000,206338.000000,9.404700e+04,206817.000000
mean,104151.500000,6.305383e+04,2012.098241,1.502768e+05,151.836281,1882.567147,3.191564e+05,4.637138
std,60132.329574,8.665967e+04,6.998414,2.937447e+06,77.683546,729.609660,7.291396e+07,0.768559
min,0.000000,5.000000e+02,1915.000000,1.000000e+00,1.000000,400.000000,1.000000e+00,1.000000
25%,52075.750000,1.780000e+04,2008.000000,5.300000e+04,105.000000,1461.000000,1.200000e+02,5.000000
50%,104151.500000,3.570000e+04,2013.000000,1.445660e+05,136.000000,1798.000000,1.400000e+02,5.000000
75%,156227.250000,7.599000e+04,2017.000000,2.060000e+05,172.000000,1997.000000,1.640000e+02,5.000000
max,208303.000000,6.999000e+06,2021.000000,1.111111e+09,1398.000000,8400.000000,2.000000e+10,55.000000

In [35]:
#Information about categorical columns

df_raw.describe(include = ['object'])

/var/folders/s_/9j10gw751dgb6tbppsps9d7w0000gn/T/ipykernel_68872/1442629724.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df_raw.describe(include = ['object'])

,Currency,Condition,Vehicle_brand,Vehicle_model,Vehicle_version,Vehicle_generation,Fuel_type,Drive,Transmission,Type,Colour,Origin_country,First_owner,First_registration_date,Offer_publication_date,Offer_location,Features
count,208304,208304,208304,208304,138082,147860,208304,193228,207825,208304,208304,118312,65094,86445,208304,208304,208304
unique,2,2,108,1203,19056,569,8,5,2,9,14,37,1,8441,41,13635,177211
top,PLN,Used,Volkswagen,Astra,2.0 TDI,II (2012-),Gasoline,Front wheels,Manual,SUV,black,Poland,Yes,01/01/2017,03/05/2021,"Stalowa 16 - 41-506 Chorzów, Śląskie (Polska)",[]
freq,208034,182850,18455,5302,888,3758,99352,139944,132889,41587,50355,57127,65094,216,26561,1329,13337

## 4. Duplicate Check

- Check if there are any duplicated indexes

In [11]:
print(df_raw.duplicated("Index").sum())

0

- Check if there are any duplicates based on core features, such as condition, vechicle brand, model and version, production year, fuel type, milleage etc.

In [25]:
core_features = ['Condition', 'Vehicle_brand', 'Vehicle_model', 'Vehicle_version', 'Production_year', 'Power_HP'
                 , 'Fuel_type', 'Colour', 'Mileage_km', 'Transmission']

print(df_raw.duplicated(subset = core_features).sum())

print(df_raw.duplicated(subset = core_features + ['Price']).sum())

8805
3203

- View the potential duplicates

In [26]:
all_duplicates = df_raw.duplicated(subset = core_features, keep = False)

df_duplicates_comparison = df_raw[all_duplicates].sort_values(by = core_features)

df_duplicates_comparison[core_features + ['Price']].head(20)

,Condition,Vehicle_brand,Vehicle_model,Vehicle_version,Production_year,Power_HP,Fuel_type,Colour,Mileage_km,Drive,Transmission,Price
0,New,Abarth,595,NaN,2021,145.0,Gasoline,gray,1.0,Front wheels,Manual,86200
9,New,Abarth,595,NaN,2021,145.0,Gasoline,gray,1.0,Front wheels,Manual,93100
83,New,Aixam,City,NaN,2021,8.0,Diesel,gray,1.0,Front wheels,Automatic,78900
127,New,Aixam,City,NaN,2021,8.0,Diesel,gray,1.0,Front wheels,Automatic,75900
144,New,Aixam,Other,NaN,2021,4.0,Diesel,other,1.0,NaN,Automatic,13426
132583,New,Aixam,Other,NaN,2021,4.0,Diesel,other,1.0,NaN,Automatic,13426
143,New,Aixam,Other,NaN,2021,8.0,Diesel,other,1.0,NaN,Automatic,14143
132580,New,Aixam,Other,NaN,2021,8.0,Diesel,other,1.0,NaN,Automatic,14143
198,New,Aixam,Other,NaN,2021,8.0,Diesel,white,1.0,Front wheels,Automatic,7399
132965,New,Aixam,Other,NaN,2021,8.0,Diesel,white,1.0,Front wheels,Automatic,7399
152,New,Aixam,Other,NaN,2021,8.0,Diesel,white,1.0,NaN,Automatic,9673
168,New,Aixam,Other,NaN,2021,8.0,Diesel,white,1.0,NaN,Automatic,9286
132625,New,Aixam,Other,NaN,2021,8.0,Diesel,white,1.0,NaN,Automatic,9673
132702,New,Aixam,Other,NaN,2021,8.0,Diesel,white,1.0,NaN,Automatic,9286
141,New,Aixam,Other,NaN,2021,12.0,Electric,other,1.0,NaN,Automatic,18448
142,New,Aixam,Other,NaN,2021,12.0,Electric,other,1.0,NaN,Automatic,17731
132577,New,Aixam,Other,NaN,2021,12.0,Electric,other,1.0,NaN,Automatic,18448
132578,New,Aixam,Other,NaN,2021,12.0,Electric,other,1.0,NaN,Automatic,17731
1004,New,Alfa Romeo,Giulia,2.0 Turbo Business,2021,200.0,Gasoline,white,1.0,Rear wheels,Automatic,145900
1279,New,Alfa Romeo,Giulia,2.0 Turbo Business,2021,200.0,Gasoline,white,1.0,Rear wheels,Automatic,148900

- Final deduplication

In [ ]:
features_to_compare = ['Condition', 'Vehicle_brand', 'Vehicle_model', 'Vehicle_version'
                      , 'Production_year', 'Power_HP', 'Mileage_km', 'Fuel_type'
                      , 'Colour', 'Drive', 'Transmission', 'Type']

print(df_raw.duplicated(subset = features_to_compare).sum())
print(f'{df_raw.duplicated(subset = features_to_compare).sum()/df_raw.shape[0] * 100}%')

7937
3.810296489745756%

In [29]:
df_deduped = df_raw.drop_duplicates(subset = features_to_compare, keep = 'first')